# sudo: required
# jobs:
#   include:
#     - os: linux
#       language: node_js
#       node_js:
#         - "14.16.1"
#     - os: windows
#       language: node_js
#       node_js:
#         - "14.16.1"
#     - os: osx
#       language: node_js
#       node_js:
#         - "14.16.1"

language: node_js
node_js:
  - "12"

before_install:
  - npm i

script:
  - npm run test